#!/bin/bash -e
# $1 - $tempFile - The path to the file that holds the commit message
# $2 - $commitType - The type of the commit ()
# $3 - $commitHash - The SHA-1 commit hash.

parse_issue_key() {
    echo $1 | grep -oP "[A-Z]+[A-Z0-9_]*-[0-9]*"
}

branch_name() {
    git rev-parse --abbrev-ref HEAD
}

prepare_commit_msg () {
    issue_temp_file=$1
    current_branch=`branch_name`
    issue_key=`parse_issue_key $current_branch`

    # Add the comment to the first line.
    sed -i -e "1i$issue_key " $issue_temp_file
}


# Only Export the functions, in case the running script is not this script and there are no parameters.
if [[ $_ != $0 && $# == 0 ]]; then
  export -f parse_issue_key
  export -f prepare_commit_msg
else
  prepare_commit_msg "${@}"
  exit $?
fi
